/**
 * Soniq — Procedural UI sounds for the web.
 *
 * No audio files. No licensing. No heavy asset packs.
 * Just clean, customizable sonic feedback generated by the Web Audio API.
 *
 * @version 0.1.0
 * @license MIT
 */

class SoniqEngine {
  constructor(options = {}) {
    this.volume = options.volume ?? 0.5;
    this.context = null;
    this.master = null;
    this.compressor = null;
  }

  init() {
    if (this.context) return this.context;

    const AudioContext = window.AudioContext || window.webkitAudioContext;
    if (!AudioContext) {
      throw new Error('Soniq: Web Audio API is not supported in this environment.');
    }

    this.context = new AudioContext();
    this.compressor = this.context.createDynamicsCompressor();
    this.compressor.threshold.value = -24;
    this.compressor.knee.value = 12;
    this.compressor.ratio.value = 4;
    this.compressor.attack.value = 0.003;
    this.compressor.release.value = 0.1;

    this.master = this.context.createGain();
    this.master.gain.value = this.volume;
    this.master.connect(this.compressor);
    this.compressor.connect(this.context.destination);

    return this.context;
  }

  ensureReady() {
    const ctx = this.init();
    if (ctx.state === 'suspended') {
      ctx.resume();
    }
    return ctx;
  }

  setVolume(value) {
    this.volume = Math.max(0, Math.min(1, value));
    if (this.master) {
      this.master.gain.setTargetAtTime(this.volume, this.now(), 0.05);
    }
  }

  now() {
    return this.context ? this.context.currentTime : 0;
  }

  // ===== Building blocks =====

  tone({ freq = 440, duration = 0.1, type = 'sine', gain = 0.5, attack = 0.005, decay = 0.05, pitchEnv = null } = {}) {
    const ctx = this.ensureReady();
    const t0 = this.now();

    const osc = ctx.createOscillator();
    const gainNode = ctx.createGain();

    osc.type = type;
    osc.frequency.setValueAtTime(freq, t0);

    if (pitchEnv) {
      osc.frequency.exponentialRampToValueAtTime(pitchEnv.to, t0 + duration);
    }

    gainNode.gain.setValueAtTime(0, t0);
    gainNode.gain.linearRampToValueAtTime(gain, t0 + attack);
    gainNode.gain.setValueAtTime(gain, t0 + duration - decay);
    gainNode.gain.exponentialRampToValueAtTime(0.0001, t0 + duration);

    osc.connect(gainNode);
    gainNode.connect(this.master);

    osc.start(t0);
    osc.stop(t0 + duration + 0.05);

    return this;
  }

  noise({ duration = 0.1, gain = 0.3, attack = 0.005, decay = 0.03, color = 'white' } = {}) {
    const ctx = this.ensureReady();
    const t0 = this.now();

    const bufferSize = Math.max(1, Math.ceil(ctx.sampleRate * (duration + decay + 0.05)));
    const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
    const data = buffer.getChannelData(0);

    if (color === 'pink') {
      let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        b0 = 0.99886 * b0 + white * 0.0555179;
        b1 = 0.99332 * b1 + white * 0.0750759;
        b2 = 0.96900 * b2 + white * 0.1538520;
        b3 = 0.86650 * b3 + white * 0.3104856;
        b4 = 0.55000 * b4 + white * 0.5329522;
        b5 = -0.7616 * b5 - white * 0.0168980;
        data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11;
        b6 = white * 0.115926;
      }
    } else {
      for (let i = 0; i < bufferSize; i++) {
        data[i] = Math.random() * 2 - 1;
      }
    }

    const source = ctx.createBufferSource();
    const gainNode = ctx.createGain();
    source.buffer = buffer;

    gainNode.gain.setValueAtTime(0, t0);
    gainNode.gain.linearRampToValueAtTime(gain, t0 + attack);
    gainNode.gain.setValueAtTime(gain, t0 + duration - decay);
    gainNode.gain.exponentialRampToValueAtTime(0.0001, t0 + duration);

    source.connect(gainNode);
    gainNode.connect(this.master);

    source.start(t0);
    source.stop(t0 + duration + 0.05);

    return this;
  }

  // ===== Presets =====

  click({ subtle = false } = {}) {
    return this.tone({
      freq: subtle ? 900 : 1200,
      duration: subtle ? 0.04 : 0.06,
      type: 'triangle',
      gain: subtle ? 0.15 : 0.3,
      attack: 0.001,
      decay: 0.02,
      pitchEnv: { to: subtle ? 600 : 400 }
    });
  }

  hover({ subtle = true } = {}) {
    return this.tone({
      freq: 600,
      duration: 0.05,
      type: 'sine',
      gain: subtle ? 0.06 : 0.12,
      attack: 0.005,
      decay: 0.03,
      pitchEnv: { to: 800 }
    });
  }

  toggle(on = true) {
    if (on) {
      return this.tone({
        freq: 300,
        duration: 0.08,
        type: 'sine',
        gain: 0.25,
        attack: 0.005,
        decay: 0.03,
        pitchEnv: { to: 500 }
      });
    }
    return this.tone({
      freq: 500,
      duration: 0.08,
      type: 'sine',
      gain: 0.2,
      attack: 0.005,
      decay: 0.03,
      pitchEnv: { to: 300 }
    });
  }

  notification({ urgent = false } = {}) {
    const ctx = this.ensureReady();
    const t0 = this.now();
    const baseFreq = urgent ? 880 : 660;
    const notes = urgent ? [baseFreq, baseFreq] : [baseFreq, baseFreq * 1.25];

    notes.forEach((freq, i) => {
      this.tone({
        freq,
        duration: 0.12,
        type: 'sine',
        gain: 0.25,
        attack: 0.01,
        decay: 0.05
      });
    });

    return this;
  }

  success() {
    this.tone({
      freq: 523.25,
      duration: 0.12,
      type: 'sine',
      gain: 0.2,
      attack: 0.005,
      decay: 0.04
    });
    this.tone({
      freq: 659.25,
      duration: 0.15,
      type: 'sine',
      gain: 0.2,
      attack: 0.005,
      decay: 0.04
    });
    this.tone({
      freq: 783.99,
      duration: 0.25,
      type: 'sine',
      gain: 0.25,
      attack: 0.01,
      decay: 0.15
    });
    return this;
  }

  error() {
    this.tone({
      freq: 180,
      duration: 0.25,
      type: 'sawtooth',
      gain: 0.2,
      attack: 0.01,
      decay: 0.12,
      pitchEnv: { to: 120 }
    });
    this.noise({
      duration: 0.15,
      gain: 0.08,
      attack: 0.005,
      decay: 0.08,
      color: 'white'
    });
    return this;
  }

  type({ subtle = true } = {}) {
    return this.noise({
      duration: 0.02,
      gain: subtle ? 0.04 : 0.08,
      attack: 0.001,
      decay: 0.01,
      color: 'white'
    });
  }

  swipe({ direction = 'right' } = {}) {
    const startFreq = direction === 'right' ? 200 : 800;
    const endFreq = direction === 'right' ? 800 : 200;
    return this.tone({
      freq: startFreq,
      duration: 0.2,
      type: 'sine',
      gain: 0.15,
      attack: 0.02,
      decay: 0.05,
      pitchEnv: { to: endFreq }
    });
  }

  pop() {
    return this.tone({
      freq: 400,
      duration: 0.08,
      type: 'sine',
      gain: 0.25,
      attack: 0.005,
      decay: 0.04,
      pitchEnv: { to: 600 }
    });
  }
}

// ===== Default instance for named exports =====
const defaultSoniq = new SoniqEngine();

export { SoniqEngine as Soniq };
export const init = () => defaultSoniq.init();
export const setVolume = (v) => defaultSoniq.setVolume(v);
export const click = (opts) => defaultSoniq.click(opts);
export const hover = (opts) => defaultSoniq.hover(opts);
export const toggle = (on) => defaultSoniq.toggle(on);
export const notification = (opts) => defaultSoniq.notification(opts);
export const success = () => defaultSoniq.success();
export const error = () => defaultSoniq.error();
export const type = (opts) => defaultSoniq.type(opts);
export const swipe = (opts) => defaultSoniq.swipe(opts);
export const pop = () => defaultSoniq.pop();
export default defaultSoniq;
